# Generated by Django 4.2.1 on 2023-12-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='department',
        ),
        migrations.AddField(
            model_name='food',
            name='department',
            field=models.ManyToManyField(to='api.department'),
        ),
    ]
